// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: pkg/domain/chromecast/proto/authority_keys.proto

package authority

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorityKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*AuthorityKeys_Key `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (x *AuthorityKeys) Reset() {
	*x = AuthorityKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorityKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityKeys) ProtoMessage() {}

func (x *AuthorityKeys) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityKeys.ProtoReflect.Descriptor instead.
func (*AuthorityKeys) Descriptor() ([]byte, []int) {
	return file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorityKeys) GetKeys() []*AuthorityKeys_Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

type AuthorityKeys_Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint []byte `protobuf:"bytes,1,req,name=fingerprint" json:"fingerprint,omitempty"`
	PublicKey   []byte `protobuf:"bytes,2,req,name=public_key,json=publicKey" json:"public_key,omitempty"`
}

func (x *AuthorityKeys_Key) Reset() {
	*x = AuthorityKeys_Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorityKeys_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityKeys_Key) ProtoMessage() {}

func (x *AuthorityKeys_Key) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityKeys_Key.ProtoReflect.Descriptor instead.
func (*AuthorityKeys_Key) Descriptor() ([]byte, []int) {
	return file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AuthorityKeys_Key) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *AuthorityKeys_Key) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_pkg_domain_chromecast_proto_authority_keys_proto protoreflect.FileDescriptor

var file_pkg_domain_chromecast_proto_authority_keys_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x21, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x48, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x1a, 0x46, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0b, 0x66,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x29, 0x48, 0x03, 0x5a, 0x25, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65,
	0x63, 0x61, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x74, 0x79,
}

var (
	file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescOnce sync.Once
	file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescData = file_pkg_domain_chromecast_proto_authority_keys_proto_rawDesc
)

func file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescGZIP() []byte {
	file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescOnce.Do(func() {
		file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescData)
	})
	return file_pkg_domain_chromecast_proto_authority_keys_proto_rawDescData
}

var file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_domain_chromecast_proto_authority_keys_proto_goTypes = []interface{}{
	(*AuthorityKeys)(nil),     // 0: extensions.api.cast_channel.proto.AuthorityKeys
	(*AuthorityKeys_Key)(nil), // 1: extensions.api.cast_channel.proto.AuthorityKeys.Key
}
var file_pkg_domain_chromecast_proto_authority_keys_proto_depIdxs = []int32{
	1, // 0: extensions.api.cast_channel.proto.AuthorityKeys.keys:type_name -> extensions.api.cast_channel.proto.AuthorityKeys.Key
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_domain_chromecast_proto_authority_keys_proto_init() }
func file_pkg_domain_chromecast_proto_authority_keys_proto_init() {
	if File_pkg_domain_chromecast_proto_authority_keys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorityKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorityKeys_Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_domain_chromecast_proto_authority_keys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_domain_chromecast_proto_authority_keys_proto_goTypes,
		DependencyIndexes: file_pkg_domain_chromecast_proto_authority_keys_proto_depIdxs,
		MessageInfos:      file_pkg_domain_chromecast_proto_authority_keys_proto_msgTypes,
	}.Build()
	File_pkg_domain_chromecast_proto_authority_keys_proto = out.File
	file_pkg_domain_chromecast_proto_authority_keys_proto_rawDesc = nil
	file_pkg_domain_chromecast_proto_authority_keys_proto_goTypes = nil
	file_pkg_domain_chromecast_proto_authority_keys_proto_depIdxs = nil
}
